# GitHub Action
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions

name: NPM Publish
description: Fast, easy publishing to NPM

author: James Messinger
branding:
  color: blue
  icon: package

inputs:
  token:
    description: The NPM access token to use when publishing
    required: true

  registry:
    description: The NPM registry URL to use
    required: false
    default: https://registry.npmjs.org/

  package:
    description: The path of your package.json file
    required: false
    default: package.json

  check-version:
    description: Only publish if the version in package.json differs from the latest on NPM
    required: false
    default: "true"

  dry-run:
    description: If true, run with the --dry-run flag
    required: false
    default: "false"

outputs:
  type:
    description: The type of version change that occurred ("none", "major", "minor", "patch", etc.)

  version:
    description: The version that was published

  old-version:
    description: The version number that was previously published to NPM

runs:
  using: node12
  main: dist/index.js
